version: '3'
services:
  web:
    tty: true
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "2000:2000"
    volumes:
      - /app/node_modules
      - .:/app 
    